---
language: python
python: 2.7

before_install:
    - sudo apt-get update -qq

install:
    # Install Ansible
    - pip install ansible

    # Tell us where the roles are
    - "printf '[defaults]\nroles_path = ../' > ansible.cfg"


script:
    - ansible-playbook -i tests/inventory tests/test.yml --check-syntax
    - ansible-playbook -i tests/inventory tests/test.yml --connection=local

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/